FORMAT: 1A
HOST: https://api.revolt.chat

# Revolt

# Data Structures

## User (object)
+ _id: 01AN4Z07BY79KA1307SR9X4MV3 (string, required)
+ username: insert (string, required)
+ avatar (File)

# Group Users

### Fetch User [GET /users/{id}]
+ Parameters
    + id: - User ID

+ Request
    + Headers
            x-user-id: 01AN4Z07BY79KA1307SR9X4MV3
            x-session-token: 01AN4Z07BY79KA1307SR9X4MV3

+ Response 200 (application/json)
    + Attributes (User)

## sussy balls

# Data Structures

## File (object)
+ _id: 01AN4Z07BY79KA1307SR9X4MV3 (string, required)
+ tag: (string)
